---
:concurrency: 10
development:
  :concurrency: 20
production:
  :concurrency: 20
:queues:
  - [recapitulations_0_crawler, 6]
  - [recapitulations_1_crawler, 6]
  - [recapitulations_2_crawler, 6]
  - [recapitulations_3_crawler, 6]
  - [recapitulations_4_crawler, 6]
  - [recapitulations_5_crawler, 6]
  - [recapitulations_6_crawler, 6]
  - [recapitulations_7_crawler, 6]
  - [recapitulations_8_crawler, 6]
  - [recapitulations_9_crawler, 6]
  - [recapitulations_10_crawler, 6]
  - [recapitulations_11_crawler, 6]
  - [recapitulations_12_crawler, 6]
  - [recapitulations_13_crawler, 6]
  - [recapitulations_14_crawler, 6]
  - [recapitulations_15_crawler, 6]
  - [recapitulations_16_crawler, 6]
  - [recapitulations_17_crawler, 6]
  - [recapitulations_18_crawler, 6]
  - [recapitulations_19_crawler, 6]
  - [recapitulations_20_crawler, 6]
  - [provinces_0_crawler, 1]
  - [states_0_crawler, 2]
  - [states_1_crawler, 2]
  - [districts_0_crawler, 3]
  - [districts_1_crawler, 3]
  - [districts_2_crawler, 3]
  - [districts_3_crawler, 3]
  - [villages_0_crawler, 4]
  - [villages_1_crawler, 4]
  - [villages_2_crawler, 4]
  - [villages_3_crawler, 4]
  - [villages_4_crawler, 4]
  - [villages_5_crawler, 4]
  - [polling_stations_0_crawler, 5]
  - [polling_stations_1_crawler, 5]
  - [polling_stations_2_crawler, 5]
  - [polling_stations_3_crawler, 5]
  - [polling_stations_4_crawler, 5]
  - [polling_stations_5_crawler, 5]
  - [polling_stations_6_crawler, 5]
  - [polling_stations_7_crawler, 5]
  - [polling_stations_8_crawler, 5]
  - [polling_stations_9_crawler, 5]
  - [polling_stations_10_crawler, 5]
  - recapitulation_runner
  - place_runner
  - critical
  - default
  - low
